user_interaction_task:
  description: >
    Understand the user's query ("{query}") and delegate tasks to the appropriate agents to retrieve and process data.
  expected_output: >
    A clear and concise task delegation to the appropriate agents in the format specified.
  agent: user_agent

database_query_task:
  description: >
    Search for relevant information for the query "{query} within the knowledge directory.
    Ensure all available files are thoroughly scanned, and provide precise references for all retrieved data necessary.
  expected_output: >
    A list of the relevant information about from the database files that are usefull to "{query}".
  agent: database_agent

data_processing_task:
  description: >
    Process and transform the retrieved data for the query "{query}" to ensure it satisfies the user's needs. 
    Upon completion, report the result to the appropriate downstream agents for further processing.
  expected_output: >
    The processed data needed to respond to the user's query "{query}" in a clear, concise, and relevant manner.
  agent: data_processing_agent

geometric_mean_task:
  description: >
    Use the tool to calculate the geometric mean of the numbers in the list of numbers.
  expected_output: >
    The geometric mean of the numbers in the list of numbers.
  agent: geometric_mean_agent
